### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [baidu/openrasp#297]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by CaledoniaProject** [comment]
Use "openrasp-support AT baidu.com".

**Comment by CaledoniaProject** [comment]
Created SECURITY.md and updated README.md

**Comment by CaledoniaProject** [comment]
I've closed the issue there as it is invalid. 

1. The latest plugin [is stored here](https://github.com/baidu/openrasp/blob/master/plugins/official/plugin.js) instead of rasp-cloud.
2. You should run actual test instead of static analysis.
3. The host is only resolved if the Application has already resolved it once.
